# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uYzz9C2G6y_nkY4q-ye5F5I1gWU0Y_5
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# --- Constants ---
G = 6.6743e-11
AU = 1.495978707e11
M_sun = 1.989e30

# Planet masses and orbital radii (m)
M_earth, R_earth = 5.9742e24, 1.0 * AU
M_mer, R_mer = 3.285e23, 0.39 * AU
M_ven, R_ven = 4.867e24, 0.72 * AU
M_mar, R_mar = 6.42e23, 1.52 * AU

# Scale factor (to fit in the plot window)
Scale = 250 / AU

# --- Orbital angular speeds (Kepler's law approximation) ---
# omega = sqrt(G M_sun / r^3)
omega_earth = np.sqrt(G * M_sun / R_earth**3)
omega_mer   = np.sqrt(G * M_sun / R_mer**3)
omega_ven   = np.sqrt(G * M_sun / R_ven**3)
omega_mar   = np.sqrt(G * M_sun / R_mar**3)

# --- Figure setup ---
fig, ax = plt.subplots(figsize=(6,6))
ax.set_xlim(-250,250)
ax.set_ylim(-250,250)
ax.set_aspect('equal')
ax.set_title("Solar System Orbits (Scaled)")

# Sun
ax.plot(0, 0, 'yo', markersize=12, label="Sun")

# Static orbit paths (scaled)
theta = np.linspace(0, 2*np.pi, 300)
ax.plot(Scale*R_earth*np.cos(theta), Scale*R_earth*np.sin(theta), 'b--', alpha=0.3)
ax.plot(Scale*R_mer*np.cos(theta),   Scale*R_mer*np.sin(theta),   'k--', alpha=0.3)
ax.plot(Scale*R_ven*np.cos(theta),   Scale*R_ven*np.sin(theta),   'orange', alpha=0.3)
ax.plot(Scale*R_mar*np.cos(theta),   Scale*R_mar*np.sin(theta),   'r--', alpha=0.3)

# Moving planets (dots)
earth, = ax.plot([], [], 'bo', markersize=6, label="Earth")
mer,   = ax.plot([], [], 'ko', markersize=4, label="Mercury")
ven,   = ax.plot([], [], 'yo', markersize=5, label="Venus")
mar,   = ax.plot([], [], 'ro', markersize=5, label="Mars")

ax.legend(loc='upper right')

# --- Update function ---
def update(frame):
    t = frame * 1e4  # time step (arbitrary scaling)

    # Orbital positions (scaled)
    x_e, y_e = Scale * R_earth * np.cos(omega_earth * t), Scale * R_earth * np.sin(omega_earth * t)
    x_mer, y_mer = Scale * R_mer * np.cos(omega_mer * t), Scale * R_mer * np.sin(omega_mer * t)
    x_ven, y_ven = Scale * R_ven * np.cos(omega_ven * t), Scale * R_ven * np.sin(omega_ven * t)
    x_mar, y_mar = Scale * R_mar * np.cos(omega_mar * t), Scale * R_mar * np.sin(omega_mar * t)

    # Update planet positions
    earth.set_data([x_e], [y_e])
    mer.set_data([x_mer], [y_mer])
    ven.set_data([x_ven], [y_ven])
    mar.set_data([x_mar], [y_mar])

    return earth, mer, ven, mar

# --- Animate ---
ani = FuncAnimation(fig, update, frames=500, interval=30, blit=True)
HTML(ani.to_jshtml())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# --- Parameters ---
r0_list = [1.0, 1.2, 0.8, 1.5]   # initial radii for 4 points
omega_list = [0.15, 0.12, 0.18, 0.1]  # angular speeds
k_list = [0.01, 0.012, 0.009, 0.008]  # inward spiral rates
colors = ['b', 'g', 'r', 'y']  # colors for the points

fig, ax = plt.subplots(figsize=(6,6))
ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)
ax.set_aspect('equal')
ax.set_facecolor('black')  # black background
ax.set_title("Particles Spiraling into a Black Hole", color='white')

# Black hole at center
ax.plot(0, 0, 'ko', markersize=15)

# Moving points
points = []
for c in colors:
    p, = ax.plot([], [], 'o', color=c, markersize=6)
    points.append(p)

# --- Update function ---
def update(frame):
    t = frame
    for i, p in enumerate(points):
        r = r0_list[i] * np.exp(-k_list[i] * t)
        theta = omega_list[i] * t
        x = r * np.cos(theta)
        y = r * np.sin(theta)
        p.set_data([x], [y])
    return points

ani = FuncAnimation(fig, update, frames=500, interval=50, blit=True)
HTML(ani.to_jshtml())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import HTML

# --- Parameters ---
num_particles = 50
r0 = np.random.uniform(0.8, 1.5, num_particles)  # initial radius
omega = np.random.uniform(0.1, 0.2, num_particles)
k = np.random.uniform(0.005, 0.01, num_particles)
colors = plt.cm.plasma(np.linspace(0,1,num_particles))  # colorful particles
z_amp = 0.1 * np.random.uniform(0.5, 1.0, num_particles)  # vertical motion amplitude
z_freq = np.random.uniform(0.5, 1.5, num_particles)

# --- Figure setup ---
fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')
ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
ax.set_zlim(-0.5,0.5)
ax.set_facecolor('black')
ax.view_init(elev=30, azim=45)  # camera angle
ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
ax.set_title("3D Accretion Disk around Black Hole", color='white')

# Black hole at center
ax.scatter(0,0,0,color='k',s=100)

# Create particle points
points = []
for i in range(num_particles):
    p, = ax.plot([], [], [], 'o', color=colors[i], markersize=4)
    points.append(p)

# --- Update function ---
def update(frame):
    t = frame
    for i, p in enumerate(points):
        r = r0[i] * np.exp(-k[i]*t)
        theta = omega[i]*t
        z = z_amp[i] * np.sin(z_freq[i]*theta)
        x = r * np.cos(theta)
        y = r * np.sin(theta)
        p.set_data([x], [y])
        p.set_3d_properties([z])
    return points

# --- Animate ---
ani = FuncAnimation(fig, update, frames=800, interval=30, blit=False)
HTML(ani.to_jshtml())



import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import HTML

# --- Parameters ---
num_particles = 200                # number of particles in disk
max_radius = 1.5                   # initial outer radius
min_radius = 0.2                   # closest approach to black hole
omega = np.random.uniform(0.1, 0.3, num_particles)  # angular speeds
k = np.random.uniform(0.002, 0.008, num_particles)  # spiral-in rate
colors = plt.cm.plasma(np.linspace(0,1,num_particles))  # color map
z_amp = 0.05 * np.random.uniform(0.5, 1.0, num_particles)  # vertical motion
z_freq = np.random.uniform(0.5, 1.5, num_particles)

# Random initial radii
r0 = np.random.uniform(min_radius, max_radius, num_particles)

# --- Figure setup ---
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111, projection='3d')
ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
ax.set_zlim(-0.5,0.5)
ax.set_facecolor('black')
ax.view_init(elev=30, azim=45)
ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
ax.set_title("3D Accretion Disk around Black Hole", color='white')

# Black hole at center
ax.scatter(0,0,0,color='k',s=120)

# Create particle points
points = []
for i in range(num_particles):
    p, = ax.plot([], [], [], 'o', color=colors[i], markersize=3, alpha=0.8)
    points.append(p)

# Store trails
trail_length = 20
x_trails = np.zeros((num_particles, trail_length))
y_trails = np.zeros((num_particles, trail_length))
z_trails = np.zeros((num_particles, trail_length))
lines = []
for i in range(num_particles):
    line, = ax.plot([], [], [], color=colors[i], alpha=0.4)
    lines.append(line)

# --- Update function ---
def update(frame):
    t = frame
    for i, p in enumerate(points):
        # Spiral radius decays
        r = r0[i] * np.exp(-k[i]*t)
        theta = omega[i]*t
        z = z_amp[i] * np.sin(z_freq[i]*theta)
        x = r * np.cos(theta)
        y = r * np.sin(theta)

        # Update particle
        p.set_data([x], [y])
        p.set_3d_properties([z])

        # Update trails
        x_trails[i] = np.roll(x_trails[i], -1)
        y_trails[i] = np.roll(y_trails[i], -1)
        z_trails[i] = np.roll(z_trails[i], -1)
        x_trails[i,-1] = x
        y_trails[i,-1] = y
        z_trails[i,-1] = z
        lines[i].set_data(x_trails[i], y_trails[i])
        lines[i].set_3d_properties(z_trails[i])

    # Slowly rotate camera
    ax.view_init(elev=30, azim=45 + frame*0.3)
    return points + lines

# --- Animate ---
ani = FuncAnimation(fig, update, frames=800, interval=30, blit=False)
HTML(ani.to_jshtml())

